export const MEDIA_ERROR_CODES = [
  'FFMPEG_MISSING',
  'FFMPEG_EXECUTION_FAILED',
  'VIDEO_VALIDATION_FAILED',
  'CODEC_NOT_SUPPORTED',
  'VIDEO_IMPORT_FAILED',
  'TRANSCRIPTION_FAILED',
  'SCENE_DETECTION_FAILED',
  'STORAGE_FAILED',
  'CHAPTER_SYNC_FAILED',
  'YOUTUBE_UPLOAD_FAILED',
  'COMPLIANCE_FAILED',
  'JOB_FAILED',
] as const;

export type MediaErrorCode = typeof MEDIA_ERROR_CODES[number];

export const MEDIA_ERROR_RETRYABLE: Record<MediaErrorCode, boolean> = {
  FFMPEG_MISSING: false,
  FFMPEG_EXECUTION_FAILED: true,
  VIDEO_VALIDATION_FAILED: false,
  CODEC_NOT_SUPPORTED: false,
  VIDEO_IMPORT_FAILED: true,
  TRANSCRIPTION_FAILED: true,
  SCENE_DETECTION_FAILED: true,
  STORAGE_FAILED: true,
  CHAPTER_SYNC_FAILED: false,
  YOUTUBE_UPLOAD_FAILED: true,
  COMPLIANCE_FAILED: false,
  JOB_FAILED: true,
};
